FROM debian AS numa_build

## install build tool
RUN apt update && apt install -y git make autoconf libtool

## build latest numactl
RUN git clone --depth=1 https://github.com/numactl/numactl /numactl
WORKDIR /numactl
RUN ./autogen.sh
RUN ./configure --enable-static
RUN make
RUN make install
RUN cp ./.libs/libnuma.so.1 /lib/x86_64-linux-gnu/


FROM library/memcached:latest

COPY --from=numa_build /numactl /numactl

## insert numactl into entrypoint
USER root
RUN sed -i 's,exec,exec ./numactl/numactl ${NUMA_ARG},g' /usr/local/bin/docker-entrypoint.sh
USER memcache