FROM qdrant/qdrant

## install build tool
RUN apt update && apt install -y git make autoconf libtool

## build latest numactl
RUN git clone --depth=1 https://github.com/numactl/numactl /numactl
WORKDIR /numactl
RUN ./autogen.sh
RUN ./configure --enable-static
RUN make
RUN make install
RUN cp ./.libs/libnuma.so.1 /lib/x86_64-linux-gnu/

## insert numactl into entrypoint
WORKDIR /qdrant
RUN sed -i 's,./qdrant,numactl ${NUMA_ARG} ./qdrant,g' entrypoint.sh