FROM debian:12-slim

## install build tool
RUN apt update && apt install -y wget git make autoconf libtool

## build latest numactl
RUN git clone --depth=1 https://github.com/numactl/numactl /numactl
WORKDIR /numactl
RUN ./autogen.sh
RUN ./configure --enable-static
RUN make
RUN make install
RUN cp ./.libs/libnuma.so.1 /lib/x86_64-linux-gnu/


## get MLC to /local
COPY ../../benchmarks/IntelMLC/get_mlc.sh /local/get_mlc.sh
WORKDIR /local
RUN ./get_mlc.sh


# Build a shell script because the ENTRYPOINT cannot use ENV and CMD at the same time
ENV entryscript='#!/bin/bash \n numactl ${NUMA_ARG} ./mlc "$@"'
RUN echo "$entryscript" > ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

# Run the generated shell script.
ENTRYPOINT ["./entrypoint.sh"]
